POST https://glorious-space-guacamole-jwr7xgrp5g52p6q9-3333.app.github.dev/api/auth/register
Content-Type: application/json

{
    "name": "Ayron",
    "email": "teste@gmail.com",
    "password": "1234"
}


###

POST https://glorious-space-guacamole-jwr7xgrp5g52p6q9-3333.app.github.dev/api/auth/login
Content-Type: application/json

{
    "email": "teste@gmail.com",
    "password": "1234"
}

###

GET https://glorious-space-guacamole-jwr7xgrp5g52p6q9-3333.app.github.dev/api/auth/users